---
sidebar: sidebar 
permalink: docs/task_mnode_ssh_management.html 
summary: 您可以使用NetApp混合雲控制UI或REST API UI、在管理節點上停用及啟用SSH功能、或使用REST API UI來判斷SSH支援連線功能的狀態。 
keywords: netapp, mnode, management node, ssh, disable, enable, rest api, hybrid, cloud, control, hcc 
---
= 管理管理節點上的SSH功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您可以使用REST API在管理節點（mNode）上停用、重新啟用或判斷SSH功能的狀態。預設會在管理節點上啟用提供的 SSH 功能link:task_mnode_enable_remote_support_connections.html["NetApp支援遠端支援通道（RST）工作階段存取"]。

從管理服務2.20.69開始、您可以使用NetApp混合雲控制UI在管理節點上啟用和停用SSH功能。

.您需要的產品
* * NetApp混合式雲端控制權限*：您擁有系統管理員權限。
* *叢集管理員權限*：您具有儲存叢集管理員權限。
* * Element軟體*：您的叢集執行NetApp Element 的是不支援功能的軟體11.3或更新版本。
* *管理節點*：您已部署執行版本11．3或更新版本的管理節點。
* *管理服務更新*：
+
** 若要使用 NetApp 混合雲控制 UI 、您已將更新 https://mysupport.netapp.com/site/products/all/details/mgmtservices/downloads-tab["管理服務套裝組合"^]至版本 2.20.69 或更新版本。
** 若要使用 REST API UI 、您已將更新 https://mysupport.netapp.com/site/products/all/details/mgmtservices/downloads-tab["管理服務套裝組合"^]至 2.17 版。




.選項
* <<使用NetApp混合雲控制UI在管理節點上停用或啟用SSH功能>>


您可以在之後執行下列任一工作link:task_mnode_api_get_authorizationtouse.html["驗證"]：

* <<使用API在管理節點上停用或啟用SSH功能>>
* <<使用API判斷管理節點上SSH功能的狀態>>




== 使用NetApp混合雲控制UI在管理節點上停用或啟用SSH功能

您可以在管理節點上停用或重新啟用SSH功能。在執行管理服務 2.18 或更新版本的管理節點上、預設會停用提供的 SSH 功能link:task_mnode_enable_remote_support_connections.html["NetApp支援遠端支援通道（RST）工作階段存取"]。停用SSH不會終止或中斷現有SSH用戶端工作階段與管理節點的連線。如果您停用SSH並選擇稍後重新啟用、則可以使用NetApp混合雲控制UI來執行此作業。


NOTE: 若要啟用或停用儲存叢集使用 SSH 的支援存取、您必須使用 https://docs.netapp.com/us-en/element-software/storage/task_system_manage_cluster_enable_and_disable_support_access.html["Element UI叢集設定頁面"^]。

.步驟
. 從儀表板中、選取右上角的選項功能表、然後選取*設定*。
. 在* Support Access for Management Nod*（*管理節點支援存取*）畫面中、切換交換器以啟用管理節點SSH。
. 完成疑難排解之後、請在* Support Access for Management Nod*（*管理節點支援存取*）畫面中、切換交換器以停用管理節點SSH。




== 使用API在管理節點上停用或啟用SSH功能

您可以在管理節點上停用或重新啟用SSH功能。預設會在管理節點上啟用提供的 SSH 功能link:task_mnode_enable_remote_support_connections.html["NetApp支援遠端支援通道（RST）工作階段存取"]。停用SSH不會終止或中斷現有SSH用戶端工作階段與管理節點的連線。如果停用SSH並選擇稍後重新啟用、您可以使用相同的API來執行此作業。

.API 命令
若為管理服務2.18或更新版本：

[listing]
----
curl -k -X PUT "https://<<ManagementNodeIP>/mnode/2/settings/ssh?enabled=<false/true>" -H  "accept: application/json" -H  "Authorization: Bearer ${TOKEN}"
----
若為管理服務2.17或更早版本：

[listing]
----
curl -X PUT "https://<ManagementNodeIP>/mnode/settings/ssh?enabled=<false/true>" -H  "accept: application/json" -H  "Authorization: Bearer ${TOKEN}"
----

NOTE: 您可以在link:task_mnode_api_get_authorizationtouse.html["授權"]使用時找到 API 命令所使用的承載 `${TOKEN}`方式。承載 `${TOKEN}`位於捲曲回應中。

.REST API UI步驟
. 輸入管理節點 IP 位址、然後輸入、以存取管理節點 API 服務的 REST API UI `/mnode/` ：
+
[listing]
----
https://<ManagementNodeIP>/mnode/
----
. 選擇*授權*並完成下列項目：
+
.. 輸入叢集使用者名稱和密碼。
.. 輸入用戶端 ID 為 `mnode-client`。
.. 選取*授權*以開始工作階段。
.. 關閉視窗。


. 從REST API UI中、選取*放置/設定、以供參考/ ssh *。
+
.. 選擇*試用*。
.. 將 *enabled* 參數設為 `false`停用 SSH 或 `true`重新啟用先前停用的 SSH 功能。
.. 選擇*執行*。






== 使用API判斷管理節點上SSH功能的狀態

您可以使用管理節點服務API、判斷管理節點上是否已啟用SSH功能。根據預設、管理節點上會啟用 SSH 。

.API 命令
若為管理服務2.18或更新版本：

[listing]
----
curl -k -X PUT "https://<<ManagementNodeIP>/mnode/2/settings/ssh?enabled=<false/true>" -H  "accept: application/json" -H  "Authorization: Bearer ${TOKEN}"
----
若為管理服務2.17或更早版本：

[listing]
----
curl -X PUT "https://<ManagementNodeIP>/mnode/settings/ssh?enabled=<false/true>" -H  "accept: application/json" -H  "Authorization: Bearer ${TOKEN}"
----

NOTE: 您可以在link:task_mnode_api_get_authorizationtouse.html["授權"]使用時找到 API 命令所使用的承載 `${TOKEN}`方式。承載 `${TOKEN}`位於捲曲回應中。

.REST API UI步驟
. 輸入管理節點 IP 位址、然後輸入、以存取管理節點 API 服務的 REST API UI `/mnode/` ：
+
[listing]
----
https://<ManagementNodeIP>/mnode/
----
. 選擇*授權*並完成下列項目：
+
.. 輸入叢集使用者名稱和密碼。
.. 輸入用戶端 ID 為 `mnode-client`。
.. 選取*授權*以開始工作階段。
.. 關閉視窗。


. 從REST API UI中、選取* Get /setsettings（取得/設定）、以供參考/ ssh *。
+
.. 選擇*試用*。
.. 選擇*執行*。




[discrete]
== 如需詳細資訊、請參閱

* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server的VMware vCenter外掛程式NetApp Element"^]

