---
sidebar: sidebar 
permalink: docs/task_mnode_multi_vcenter_config.html 
summary: 您可以使用REST API UI、將NetApp混合雲控制設定為使用多個vCenter。 
keywords: netapp, mnode, management node, multi-vcenter, hci 
---
= 為多個vCenter設定NetApp混合雲控制
:allow-uri-read: 


[role="lead"]
您可以設定NetApp混合雲控制、從兩個或多個vCenter管理未使用連結模式的資產。

當您需要新增資產以進行最近擴充的安裝、或是新資產未自動新增至組態時、您應該在初始安裝之後使用此程序。使用這些API新增最近新增至安裝的資產。

.您需要的產品
* 您的叢集版本執行的是 NetApp Element 軟體 11.3 或更新版本。
* 您已部署執行11.3版或更新版本的管理節點。


.步驟
. link:task_mnode_add_assets.html["新增vCenter做為控制器資產"]至管理節點組態。
. link:task_mnode_add_assets.html["新增運算節點做為運算資產"]至管理節點組態。
+

NOTE: 您可能需要link:task_hcc_edit_bmc_info.html["變更運算節點的BMC認證"]解決 `Hardware ID not available` NetApp 混合雲控制中指出的或 `Unable to Detect`錯誤。

. 重新整理管理節點上的庫存服務API：
+
[listing]
----
https://<ManagementNodeIP>/inventory/1/
----
+

NOTE: 此外、您也可以在NetApp混合雲控制UI中等待15分鐘、以便更新庫存。

+
.. 選擇*授權*並完成下列項目：
+
... 輸入叢集使用者名稱和密碼。
... 輸入用戶端 ID 為 `mnode-client`。
... 選取*授權*以開始工作階段。
... 關閉視窗。


.. 從REST API UI中、選取*「Get Rise/Installations」*。
.. 選擇*試用*。
.. 選擇*執行*。
.. 從響應中複製安裝資產 ID (`"id"`）。
.. 從REST API UI中選取* Get /Installations/{id}*。
.. 選擇*試用*。
.. 將 Refresh （刷新）設置爲 `True`。
.. 將安裝資產ID貼到* id*欄位。
.. 選擇*執行*。


. 重新整理NetApp混合雲控制瀏覽器、查看變更內容。


[discrete]
== 如需詳細資訊、請參閱

* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server的VMware vCenter外掛程式NetApp Element"^]

