---
sidebar: sidebar 
permalink: docs/task_nde_disable_lacp_individual.html 
summary: '瞭解如何在部署 NetApp HCI 之後停用 `lacp-individual`已設定交換器上的命令。' 
keywords: netapp, hci, deployment, review, deploy 
---
= 在已設定的交換器上停用「lacp個別」命令
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
根據預設、 Mellanox `lacp-individual` 交換器命令和 Cisco 交換器 `lacp suspend-individual`命令會保留設定的 POST 部署。安裝後不需要此命令；如果仍設定此命令、則在疑難排解或重新開機交換器時、可能會造成磁碟區存取問題。部署後、您應該檢查每個 Mellanox 交換器和 Cisco 交換器組態、然後移除 `lacp-individual`或 `lacp suspend-individual`命令。

.步驟
. 使用SSH開啟交換器的工作階段。
. 顯示執行中的組態：
+
`show running-config`

. 檢查或 `lacp suspend-individual`命令的交換器組態輸出 `lacp-individual`。
+

NOTE:  `xxx-xxx`為使用者提供的介面編號。如有需要、您可以顯示多機箱連結集合群組介面來存取介面編號： `show mlag interfaces`

+
.. 對於Mellanox交換器、請檢查輸出是否包含下列行：
+
`interface mlag-port-channel xxx-xxx lacp-individual enable force`

.. 對於Cisco交換器、請檢查輸出是否包含下列行：
+
`interface mlag-port-channel xxx-xxx lacp suspend-individual enable force`



. 如果存在命令、請將其從組態中移除。
+
.. 對於Mellanox交換器：
+
`no interface mlag-port-channel xxx-xxx lacp-individual enable force`

.. 對於 Cisco 交換器：
`no interface mlag-port-channel xxx-xxx lacp suspend-individual enable force`


. 針對組態中的每個交換器重複這些步驟。


[discrete]
== 如需詳細資訊、請參閱

* https://kb.netapp.com/Advice_and_Troubleshooting/Flash_Storage/SF_Series/SolidFire_Bond10G_goes_down_when_flapping_an_interface_during_troubleshooting["儲存節點在疑難排解期間當機"^]

